version: "1.0"

packages:
  apt:
    - vim
    - git
    - "invalid-package*name"  # This should trigger a validation error
  
files:
  vimrc:
    source: "dotfiles/.vimrc"  # This file doesn't exist - should trigger error
    destination: "~/.vimrc"
    mode: "644"

dconf:
  settings:
    "invalid-path": "'value'"  # Missing leading slash - should trigger error
    "/org/gnome/desktop/interface/gtk-theme": "'Adwaita'"