.TH VALIDATE 1 "2025-07-27" "validate" "Validate configuration file"
.SH NAME
validate - Validate configuration file
.SH SYNOPSIS
\fBvalidate\fP [\fIoptions\&.\&.\&.\fP] [\fIargument\&.\&.\&.\fP]
.SH DESCRIPTION
Validate the configuration file for syntax errors, missing files, 
.PP
and other issues without making any changes to the system\&.
.SH OPTIONS
.TP
\fB--v --verbose\fP
Show detailed validation information
.SH SEE ALSO
configr(1), configr-validate(1)