.TH COMPLETION 1 "2025-07-27" "completion" "Generate shell completion scripts"
.SH NAME
completion - Generate shell completion scripts
.SH SYNOPSIS
\fBcompletion\fP [\fIoptions\&.\&.\&.\fP] [\fIargument\&.\&.\&.\fP]
.SH DESCRIPTION
Generate shell completion scripts for configr\&.
.PP
.PP
The completion script for the given shell will be written to stdout\&.
.PP
To load completions, add the output to your shell's completion directory
.PP
or source it directly\&.
.SH SEE ALSO
configr(1), configr-completion(1)